# The URL the site will be built for
base_url = "https://henrifrancois.github.io"

title = "Henri François"
description = "A dev blog"

theme = "after-dark"
after_dark_title = "Henri François"

[extra]
author = "Henri François"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "https://github.com/henrifrancois", name = "Github"},
    {url = "https://twitter.com/henri_franc", name = "Twitter"},
]
# taxonomies are not yet added as I don't yet need them, since I have no posts
