# The URL the site will be built for
base_url = "https://henrifrancois.github.io"

title = "Henri François"
description = "A dev blog"

theme = "after-dark"
after_dark_title = "Henri François"

[extra]
author = "Henri François"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "https://hachyderm.io/@henrif", name = "Mastodon/Hachyderm"},
]
